# runs on any comment matching the format `/tag <tagname> <commit>`
name: Comment Bot
on:
  issue_comment: {types: [created]}
  pull_request_review_comment: {types: [created]}
jobs:
  tag:
    runs-on: ubuntu-latest
    permissions: {contents: write, pull-requests: write, issues: write}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN || github.token }}
    - uses: casperdcl/comment-bot@v1
      with:
        token: ${{ secrets.GH_TOKEN || github.token }}
